apiVersion: v2
name: platform
version: 1.1.0
description: Unified Helm chart for Trading + Monitoring Stack
dependencies:
  - name: prometheus
    version: 1.0.0
    repository: "file://charts/prometheus"
  - name: grafana
    version: 1.0.0
    repository: "file://charts/grafana"
  - name: loki
    version: 1.0.0
    repository: "file://charts/loki"
  - name: promtail
    version: 1.0.0
    repository: "file://charts/promtail"

