prometheus:
  enabled: true
  server:
    service:
      type: NodePort
      nodePort: 30900
    nodeSelector:
      role: monitor

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30300
  adminUser: admin
  adminPassword: admin
  nodeSelector:
    role: monitor

loki:
  enabled: true
  auth_enabled: false
  storage:
    type: filesystem
  nodeSelector:
    role: monitor

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
  nodeSelector:
    role: monitor
